// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/omalloc/contrib/kratos/health"
	"github.com/omalloc/contrib/kratos/registry"
	"github.com/omalloc/kratos-agent/internal/biz"
	"github.com/omalloc/kratos-agent/internal/conf"
	"github.com/omalloc/kratos-agent/internal/data"
	"github.com/omalloc/kratos-agent/internal/server"
	"github.com/omalloc/kratos-agent/internal/server/adapter"
	"github.com/omalloc/kratos-agent/internal/service"
	"github.com/omalloc/kratos-agent/pkg/cluster"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(bootstrap *conf.Bootstrap, confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	protobufRegistry := server.NewRegistryConfig(bootstrap)
	client, cleanup, err := registry.NewEtcd(protobufRegistry)
	if err != nil {
		return nil, nil, err
	}
	registrar := registry.NewRegistrar(client)
	criUsecase := biz.NewCRIUsecase(logger)
	v, err := cluster.NewClients(logger, bootstrap)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	clusterUsecase := biz.NewClusterUsecase(logger, v)
	agentService := service.NewAgentService(logger, criUsecase, clusterUsecase)
	grpcServer := server.NewGRPCServer(confServer, agentService, logger)
	httpServer := server.NewHTTPServer(confServer, agentService, logger)
	dataData, cleanup2, err := data.NewData(confData, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	etcd := adapter.NewETCDChecker(client)
	v2 := server.NewChecker(dataData, etcd, agentService)
	healthServer := health.NewServer(v2, logger, httpServer)
	app := newApp(logger, registrar, grpcServer, httpServer, healthServer)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
