server:
  http:
    addr: 0.0.0.0:2381
    timeout: 5s
  grpc:
    addr: 0.0.0.0:2382
    timeout: 5s
data:
  database:
    driver: mysql
    source: root:root@tcp(127.0.0.1:3306)/test
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
